import { Badge } from "flowbite-react";
import { Topic } from "@/types/problem";

type TopicBadgeProps = {
  topic: Topic
};

// Generated by ChatGPT
function startCase(str: string): string {
  return str
    // replace hyphens and underscores with space
    .replace(/[-_]/g, ' ')
    .replace(/\w\S*/g, word =>
      word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
    );
}

export default function TopicBadge({ topic }: TopicBadgeProps) {
  const topicLabelOverride = {
    "depth-first-search": "Depth-First Search",
    "breadth-first-search": "Breadth-First Search",
    "heap-priority-queue": "Heap (Priority Queue)",
    "doubly-linked-list": "Doubly-Linked List"
  };

  const topicLabel = topicLabelOverride[topic as keyof typeof topicLabelOverride] ?? startCase(topic);

  return (
    <Badge>{topicLabel}</Badge>
  );
}
